
[package]
name = "executor-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
fyrox = { git = "https://github.com/FyroxEngine/Fyrox" }
zombo = { path = "../game" }